### ISSUE TITLE
Linux Mint 17.3 Same App- Two icons in menu

### ISSUE THREAD

**Issue by theajr** [jfarthing84/cinnamon-slingshot#5]
HI. I am using slingshot in my LInux MInt 17.3 rosa. In menu slingshot show some apps twice.. Can u please let me know the solution.
![screenshot from 2016-03-10 09 29 49](https://cloud.githubusercontent.com/assets/11477078/13659011/acc5eeec-e6a2-11e5-871a-1bdbeaa8ab80.png)

**Comment by jfarthing84** [comment]
Does the same app show in two different categories?
